package com.sigeschool.domain.service.import

import com.sigeschool.domain.repository.StudentRepository
import com.sigeschool.domain.model.Student
import com.sigeschool.domain.model.StudentStatus
import com.sigeschool.domain.util.Resource
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

class StudentImporterService(
    private val studentRepository: StudentRepository,
    private val fileProcessor: FileProcessor,
    private val validator: StudentDataValidator
) {
    suspend fun importFromCsv(csvContent: String, institutionId: String): AcademicImportResult = withContext(Dispatchers.Default) {
        val rows = fileProcessor.parseCsv(csvContent)
        processRows(rows, institutionId)
    }

    suspend fun importFromExcel(byteArray: ByteArray, institutionId: String): AcademicImportResult = withContext(Dispatchers.Default) {
        val rows = fileProcessor.parseExcel(byteArray)
        processRows(rows, institutionId)
    }

    private suspend fun processRows(rows: List<Map<String, String>>, institutionId: String): AcademicImportResult {
        val errors = mutableListOf<ImportError>()
        val warnings = mutableListOf<ImportError>()
        var inserted = 0
        var updated = 0

        rows.forEachIndexed { index, data ->
            val rowIndex = index + 2 // 1-based + header
            val normalizedData = data.mapKeys { HeaderNormalizer.normalize(it.key) }
            
            when (val validation = validator.validateRow(normalizedData)) {
                is ValidationResult.Valid -> {
                    try {
                        if (processStudent(normalizedData, institutionId)) inserted++ else updated++
                    } catch (e: Exception) {
                        errors.add(ImportError(rowIndex, e.message ?: "Error de procesamiento"))
                    }
                }
                is ValidationResult.Warning -> {
                    try {
                        if (processStudent(normalizedData, institutionId)) inserted++ else updated++
                        warnings.add(ImportError(rowIndex, validation.message))
                    } catch (e: Exception) {
                        errors.add(ImportError(rowIndex, e.message ?: "Error de procesamiento"))
                    }
                }
                is ValidationResult.Invalid -> {
                    errors.add(ImportError(rowIndex, validation.reason))
                }
            }
        }
        return AcademicImportResult(rows.size, inserted, updated, errors, warnings)
    }

    private suspend fun processStudent(data: Map<String, String>, institutionId: String): Boolean {
        val docId = (data["student_document_number"] ?: data["document_number"])?.trim() ?: ""
        val firstName = data["first_name"]?.trim() ?: ""
        val lastName = data["last_name"]?.trim() ?: ""
        
        val searchResults = studentRepository.searchStudents(docId)
        val existing = searchResults.firstOrNull { it.dni == docId }
        
        val isNew = existing == null
        val studentId = existing?.id ?: "" // UUID generated by repository usually, but here we might need it
        
        val student = Student(
            id = if (isNew) "" else studentId,
            institutionId = institutionId,
            nombre = firstName.uppercase(),
            apellido = lastName.uppercase(),
            dni = docId,
            email = data["email"] ?: "",
            telefono = data["phone"] ?: "",
            direccion = data["address"] ?: "",
            grado = data["cycle_selection"] ?: data["program"] ?: "",
            nombreAcudiente = "${data["guardian_first_name"] ?: ""} ${data["guardian_last_name"] ?: ""}".trim(),
            documentoAcudiente = data["parent_document_number"] ?: "",
            telefonoAcudiente = data["guardian_phone"] ?: "",
            emailAcudiente = data["guardian_email"] ?: "",
            estadoMatricula = StudentStatus.ASPIRANTE,
            sincronizado = false
        )

        if (isNew) {
            studentRepository.saveStudent(student)
        } else {
            studentRepository.saveStudent(student)
        }
        
        return isNew
    }
}
